stages:
  - build
  - deploy

build:
  image: electronuserland/builder
  stage: build
  script:
    - yarn
    - yarn build:pack --mac
  artifacts:
    expire_in: 1 day
    paths:
      - dist/*-mac.zip
  only:
    - master
